### ISSUE TITLE
图片转存失败

### ISSUE THREAD

**Issue by nangongchengfeng** [flytam/CsdnSyncHexo#42]
```bash

未提供cookie 使用爬取页面模式，页面数据可能有错误
拉取:108532985
request: get https://blog.csdn.net/qihensang/article/details/108532985
success: 1;fail: 0
拉取:101025455
request: get https://blog.csdn.net/qihensang/article/details/101025455
success: 2;fail: 0
拉取:89672985
request: get https://blog.csdn.net/qihensang/article/details/89672985
success: 3;fail: 0
输出路径 /root/csdn/out
转存图片开始
开始转存图片，共6张
TypeError: picgo_1.default is not a constructor
    at /root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:23:21
    at new Promise (<anonymous>)
    at helpUpload (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:21:15)
    at Csdn.<anonymous> (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:72:38)
    at Generator.next (<anonymous>)
    at /root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:4:12)
    at Csdn.transformImg (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:44:12)
    at Csdn.<anonymous> (/root/csdn/node_modules/csdnsynchexo/dist/extension/base.js:65:48)
TypeError: picgo_1.default is not a constructor
    at /root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:23:21
    at new Promise (<anonymous>)
    at helpUpload (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:21:15)
    at Csdn.<anonymous> (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:72:38)
    at Generator.throw (<anonymous>)
    at rejected (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:6:65)
TypeError: picgo_1.default is not a constructor
    at /root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:23:21
    at new Promise (<anonymous>)
    at helpUpload (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:21:15)
    at Csdn.<anonymous> (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:72:38)
    at Generator.throw (<anonymous>)
    at rejected (/root/csdn/node_modules/csdnsynchexo/dist/utils/transformImg.js:6:65)
图片转存失败

```
安装方式：
```bash
 npm i -g  csdnsynchexo@latest

执行：
hsync  --config   ./config.json

{
  "userId": "qihensang",
  "type": "csdn",
  "output": "./out",
  "imgConfig": "/root/csdn/img.json"
}


图片配置

{
  "accessKey": "xxxxx",
  "secretKey": "xxxx",
  "bucket": "xxxxx",
  "url": "http://image.xxxxxx.top",
  "area": "z2",
  "options": "",
  "path": "csdn/"
}



```
您好，能麻烦看一下什么问题，还是我的操作有问题，谢谢Thanks♪(･ω･)ﾉ

**Comment by flytam** [comment]
@nangongchengfeng 最新版修复了下转存相关的一些问题，可以安装最新版再试试

**Comment by nangongchengfeng** [comment]
> @nangongchengfeng 最新版修复了下转存相关的一些问题，可以安装最新版再试试
感谢大佬。

我有个建议，能否加一个参数，指定下载对应文章的id，可以单篇下载，也可以批量下载几篇
比如：
-c ‘id1，id2，id2’
这样的形式

**Comment by flytam** [comment]
> 

哈哈应该可以，我后面抽空弄一下

**Comment by flytam** [comment]
> > @nangongchengfeng 最新版修复了下转存相关的一些问题，可以安装最新版再试试
> > 感谢大佬。
> 
> 我有个建议，能否加一个参数，指定下载对应文章的id，可以单篇下载，也可以批量下载几篇 比如： -c ‘id1，id2，id2’ 这样的形式

应该可以，我后面抽空弄一下
